"""Add Board.avatar

Revision ID: 2f2e7a57805b
Revises: 9c1bc5e03556
Create Date: 2025-09-14 13:45:24.795957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2f2e7a57805b"
down_revision: Union[str, Sequence[str], None] = "9c1bc5e03556"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boards", sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("boards", sa.Column("caption", sa.String(length=255), nullable=True))
    op.alter_column("boards", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boards", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("boards", "caption")
    op.drop_column("boards", "avatar")
    # ### end Alembic commands ###
