"""Add rotate_at to session model

Revision ID: 6aea2e736e7c
Revises: a78b35e79f3c
Create Date: 2025-09-03 19:25:55.030025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aea2e736e7c'
down_revision: Union[str, Sequence[str], None] = 'a78b35e79f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rotated_at')
    # ### end Alembic commands ###
