"""Add invitation model

Revision ID: 8c19b989c7f0
Revises: d79bea6e0b59
Create Date: 2025-09-19 19:36:02.770496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from membership.model import MembershipRole


# revision identifiers, used by Alembic.
revision: str = "8c19b989c7f0"
down_revision: Union[str, Sequence[str], None] = "d79bea6e0b59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id_", sa.Uuid(), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column("invitee_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "membership_role",
            sa.Enum(
                "ADMIN",
                "MEMBER",
                name="membershiprole",
                create_type=False,
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["boards.id_"],
        ),
        sa.PrimaryKeyConstraint("id_"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitations")
    # ### end Alembic commands ###
