"""Remove Board.private field

Revision ID: 9c1bc5e03556
Revises: e9deae130cef
Create Date: 2025-09-11 11:52:12.614063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1bc5e03556'
down_revision: Union[str, Sequence[str], None] = 'e9deae130cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
