"""Remove status from invitation model

Revision ID: af6d0188ba8b
Revises: 8c19b989c7f0
Create Date: 2025-09-24 14:58:22.064220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "af6d0188ba8b"
down_revision: Union[str, Sequence[str], None] = "8c19b989c7f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "invitations",
        "membership_role",
        existing_type=sa.Enum("ADMIN", "MEMBER", name="membershiprole"),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )

    # ### end Alembic commands ###
