"""Remove membership role from invitation model

Revision ID: b2e3b0b8923c
Revises: af6d0188ba8b
Create Date: 2025-09-24 15:08:56.895801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e3b0b8923c'
down_revision: Union[str, Sequence[str], None] = 'af6d0188ba8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'membership_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('membership_role', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
