"""Add membership table

Revision ID: d79bea6e0b59
Revises: 2f2e7a57805b
Create Date: 2025-09-18 16:17:00.994739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d79bea6e0b59"
down_revision: Union[str, Sequence[str], None] = "2f2e7a57805b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memberships",
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("board_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", name="membershiprole"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["users.id_"],
        ),
        sa.PrimaryKeyConstraint("member_id", "board_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memberships")
    # ### end Alembic commands ###
